services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      - VITE_APP_WS_SERVER_URL=http://excalidraw-room:80
    networks:
      - excalidraw-network

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room
    ports:
      - "5002:80"
    restart: unless-stopped
    networks:
      - excalidraw-network

networks:
  excalidraw-network:
    driver: bridge